# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Cycle
                                 A QGIS plugin
 This plugins helps hydraulics engineers to quantify the emission in any given project. It is compatible with Hydra and Expresseau.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-08-21
        copyright            : (C) 2024 by Setec Hydratec
        email                : theophile.mounier@setec.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Cycle class from file Cycle.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .cycle import Cycle
    return Cycle(iface)
